<a href="https://colab.research.google.com/github/pushpendraraj05/happy05/blob/main/python_basics_sep4_batch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math
math.sqrt(256)

16.0

In [4]:
round(1235.66586)

1236

In [6]:
7<25

True

In [8]:
10==20

False

In [10]:
10+15

25

In [12]:
85-45

40

In [14]:
25*4

100

In [16]:
155/5

31.0

In [18]:
45==45

True

In [20]:
45!=25

True

In [22]:
45<65

True

In [25]:
45>20

True

In [34]:
(10>20) & (20>10) 

False

In [35]:
(10>20) | (20>10)

True

In [36]:
not(5==5)

False

In [38]:
# we can not compare with string data

In [39]:
#3 types of loop
#while
#for
#loop

In [44]:
i=0
while i<=5:
  print(i)
  i=i+1

0
1
2
3
4
5


In [46]:
i=0
while i<=5:
  print(i)
  i=i+1
print('loop Ends')

0
1
2
3
4
5
loop Ends


In [48]:
i=10
while i<=5:
  print(i)
  i=i+1
print('loop Ends')

loop Ends


In [50]:
range(8)

range(0, 8)

In [52]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [55]:
for i in range(6):
  print("hello world")

hello world
hello world
hello world
hello world
hello world
hello world


In [56]:
import numpy as np
from numpy.random import randn

In [65]:
x=randn()
if x>1:
  result= "greater than 1"
print(x)
print(result)

2.0506669798628416
greater than 1


In [62]:
result= None
x=randn()
if x>1:
  result="greater than 1"
print(x)
print(result)

0.6846784485209025
None


In [67]:
result= None
x=randn()
if x>1:
  result="greater than 1"
else:
  result='less than 1'
print(x)
print(result)

1.4566464462016098
greater than 1


In [86]:
result= None
x=randn()
if x>1:
  result="greater than 1"
elif x<-1:
  result="less than -1"
else:
  result="between -1 and 1"
print(x)
print(result)

0.4937616506374253
between -1 and 1


In [88]:
#creating a list
list1=[1,2,3,10,'abc',"good job",True, 20.63]

In [90]:
list1

[1, 2, 3, 10, 'abc', 'good job', True, 20.63]

In [92]:
type(list1)

list

In [94]:
#indexing in python always starts from 0
# 0 is the first term
list1[1]

2

In [97]:
# to get the last element of the list
list1[-1]

20.63

In [101]:
# list is mutuable(changable)
list1[2]="great time"
list1

[1, 2, 'great time', 10, 'abc', 'good job', True, 20.63]

In [103]:
#getting data from list or slicing
list1[2:5]
#[starting index: ending index+1]

['great time', 10, 'abc']

In [105]:
list1[::2]
#for evey 2nd element

[1, 'great time', 'abc', True]

In [107]:
#reverse the list
list1[::-1]

[20.63, True, 'good job', 'abc', 10, 'great time', 2, 1]

In [110]:
list1[::]

[1, 2, 'great time', 10, 'abc', 'good job', True, 20.63]

In [114]:
#tuple
#can not be changable
tuple1=(10,'sbc',36.55)
tuple1[1]

'sbc'

In [149]:
list3=list(range(5,11))

In [132]:
range(5,10)

range(5, 10)

In [136]:
print(list3)

[5, 6, 7, 8, 9, 10]


In [138]:
len(list3)

6

In [140]:
type(list3)

list

In [142]:
max(list3)

10

In [150]:
min(list3)

5

In [153]:
#package & module in python. 
#Array
import numpy as np

In [156]:
a=np.array(list1)
print(a)

['1' '2' 'great time' '10' 'abc' 'good job' 'True' '20.63']


In [158]:
a

array(['1', '2', 'great time', '10', 'abc', 'good job', 'True', '20.63'],
      dtype='<U32')

In [159]:
#u= unicode

In [161]:
b=np.array([2345,6789,9876,1456,-1234])

In [164]:
b.mean()

3846.4

In [166]:
b[::2]

array([ 2345,  9876, -1234])

In [171]:
b[1::2]

array([6789, 1456])

In [174]:
c=b[2:4]
c

array([9876, 1456])

In [177]:
c[:]=222
c

array([222, 222])

In [178]:
b

array([ 2345,  6789,   222,   222, -1234])